# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  lane :staging do
      # code related to building the app
      gradle(task: "assembleRelease")

      # code relating to deploying the app
      # ...

      appcenter_upload(
        api_token: "be73b70aecc295e6a04c161c542090f4b62fbaf6",
        owner_name: "maximeg-ext.bam.tech",
        owner_type: "user", # Default is user - set to organization for appcenter organizations
        app_name: "MyTestApp",
        file: "app/build/outputs/apk/release/app-release-unsigned.apk",
        notify_testers: false # Set to false if you don't want to notify testers of your new release (default: `false`)
      )
    end

end
